name = "my-knowledge-base"
compatibility_date = "2023-10-01"

[env.production]
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "D1_DATABASE"
database_name = "my-knowledge-base-db"
database_id = "39d46582-47cd-4d07-87f7-267b8670eeae"

[[kv_namespaces]]
binding = "KV_NAMESPACE"
id = "YOUR_KV_NAMESPACE_ID"